name: Deploy Dev
on:
  push:
    branches:
      - DP-2183_deploy_to_dev
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Install NPM dependencies
      run: npm install
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_DEV }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
    - name: Deploy Lambda functions
      run: SLS_DEBUG=true sls deploy -s dev