name: "Pull Request Labeler"
on:
- pull_request_target
  
jobs:
  triage:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write

    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

