name: PR Tests

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install tox
      - name: Test with tox [fastapi]
        working-directory: ./fastapi
        run: tox -e py,flake8,black
      - name: Test with tox [flask]
        working-directory: ./flask
        run: tox -e py,flake8,black
      - name: Test with tox [python]
        working-directory: ./python
        run: tox -e py,flake8,black
